### PR TITLE
Update to latest geckodriver, version 0.20.0

### PR DESCRIPTION
**Pull request by stephendonner**
Throwing this to the Travis CI wind, while I test.

### CODE REVIEW

**Comment by stephendonner** [comment]
Sweet; @jrbenny35 @davehunt thoughts?

**Comment by jrbenny35** [comment]
I wonder how the coverage decreased....

**Comment by davehunt** [comment]
@jrbenny35 coverage decreased because Firefox 59 was released, meaning we no longer excercise this code:

https://github.com/mozilla/FoxPuppet/blob/f825aa460ea9184eb0913173d6b531683f23093d/foxpuppet/windows/browser/notifications/addons.py#L40-L44

We should remove that in a separate pull request.

**Comment by stephendonner** [comment]
With https://github.com/mozilla/FoxPuppet/pull/162/commits/e0235a5895e0da7e482fb155f2fb299fe33b9bd9 "Coverage increased (+1.7%) to 100.0%", so merging in.

**Pull request merged**
