### PR TITLE
refactor(chore) Add mypy static type checking configurations

### LINKED ISSUE #314: Add mypy static type checking
Let's add a static type checking tool to this project and get all of the classes and methods to be statically typed. We can use [mypy](https://mypy-lang.org/) for this since this is what we are mainly using at Mozilla.

- [ ] Add pyright to poetry and configure it in `pyproject.toml`
- [ ] Fix all objects and methods to be type checked
- [ ] Update test files to be type checked
- [ ] Add a command to the `Makefile` to run the static type checking
- [ ] Add a test to the github actions workflow to run the type checker on pull requests. 

Here are some basic options we should use my mypy, we can adjust these later as well. These should exist within the `pyproject.toml` file.

```
[tool.mypy]
python_version = "3.12"
disable_error_code = "attr-defined"
disallow_untyped_calls = false
follow_imports = "normal"
ignore_missing_imports = true
pretty = true
show_error_codes = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
warn_unreachable = true
```

### PR DESCRIPTION
**Pull request by cashall-0**
Because

* We want  to enhance the project to use static typing 

This commit

* Adds pyright to poetry and configure it in pyproject.toml
* Fixes all objects and methods to be type checked
* Update test files to be type checked
* Add a command to the Makefile to run the static type checking
* Add a test to the github actions workflow to run the type checker on pull requests.

Fixes #314

### CODE REVIEW

**Comment by cashall-0** [comment]
Hi @b4handjr, this is a PR for issue #314. I have added the configuration for CI and pyright dependency.
Should I continue with "Fix all objects and methods to be type checked" and "Update test files to be type checked" on this same PR or would it be better to do that on a separate PR?

**Comment by b4handjr** [comment]
> Hi @b4handjr, this is a PR for issue #314. I have added the configuration for CI and pyright dependency. Should I continue with "Fix all objects and methods to be type checked" and "Update test files to be type checked" on this same PR or would it be better to do that on a separate PR?

Adding the updated files here would be fine. Also, can you please rename this PR to reference `mypy` and not `pyright`? I was deciding between mypy or pyright when I created the issue and forgot to update the title. Thanks!

**Comment by cashall-0** [comment]
> > Hi @b4handjr, this is a PR for issue #314. I have added the configuration for CI and pyright dependency. Should I continue with "Fix all objects and methods to be type checked" and "Update test files to be type checked" on this same PR or would it be better to do that on a separate PR?
> 
> Adding the updated files here would be fine. Also, can you please rename this PR to reference `mypy` and not `pyright`? I was deciding between mypy or pyright when I created the issue and forgot to update the title. Thanks!

In the implementation used, I added pyright to the dependencies, should I remove everything pyright?

**Comment by b4handjr** [comment]
> 
> In the implementation used, I added pyright to the dependencies, should I remove everything pyright?

Yes, just focus on mypy. Thank you and sorry about the confusion.

**Comment by cashall-0** [comment]
I am moving this to a new PR and deleting this one, because of a persistent conflict arising from using an old version of poetry for clarity.

**Pull request closed without merging**
