### PR TITLE
Fix breakage from Firefox 55 and coverage from Firefox ESR

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by davehunt** [comment]
Looks like coverage has been restored, and all tests are passing. Feel free to merge after reviewing if you're happy @jrbenny35.

**Comment by jrbenny35** [comment]
I like this better than supporting the older 52. Thanks!

**Comment by jrbenny35** [comment]
Could you add a note to the docs about the new support range?

**Comment by davehunt** [comment]
> Could you add a note to the docs about the new support range?

The support range hasn't changed. We always planned ESR->Nightly.. All I've done is dropped 52 and earlier, which is before ESR.

**Pull request merged**
