### PR TITLE
Rename pyup.yml to .pyup.yml

### PR DESCRIPTION
**Pull request by jayfk**
The file is called `.pyup.yml`, note the leading `.`.

### CODE REVIEW

**Comment by stephendonner** [comment]
Thanks again (as always!) @jayfk!  The PRs are already rolling in: https://github.com/mozilla/FoxPuppet/pull/154 and https://github.com/mozilla/FoxPuppet/pull/154 and https://github.com/mozilla/FoxPuppet/pull/155.

**Comment by jayfk** [comment]
Yep, no problem!

**Comment by davehunt** [comment]
My bad, sorry for wasting your time, and thank you both to @stephendonner and @jayfk!

**Comment by jayfk** [comment]
Argh, nevermind! I've heard @hackebrot is working with you now. Give him a warm welcome from me :)

**Comment by davehunt** [comment]
Indeed, we're thrilled to have him! 😄

**Pull request merged**
