### PR TITLE
chore(project): move black to dev-dependencies

### LINKED ISSUE #315: Our pyproject file has the black dependency in the wrong group.
Currently `black` is located under `dependencies`, it should be under `dev.dependencies`.

### PR DESCRIPTION
**Pull request by Temidayo32**
Because

* black is a development tool and should not be part of production dependencies

This commit

* moves black from dependencies to dev-dependencies in the poetry configuration

Fixes #315

### CODE REVIEW

**Review by b4handjr — APPROVED** [review]
R+, thanks!

**Comment by Temidayo32** [comment]
Thanks for the merge!

**Comment by b4handjr** [comment]
I had to revert this, something was wrong on my end and it merged with an incorrect title. Can you open a new one? Thanks

**Comment by Temidayo32** [comment]
Alright. I will do that right away!

**Pull request merged**
