### PR TITLE
Fix test by switching to Mozilla's tracking-protection test page

### PR DESCRIPTION
**Pull request by stephendonner**

### CODE REVIEW

**Comment by stephendonner** [comment]
Well, this bombed all the way down! 👎

**Comment by davehunt** [comment]
Did this work locally? Looking at the failing test, it's only on Nightly so I suspect that it's not related to the page we're loading. Also, the screenshot of the failure shows the tracking protection shield: https://s3.amazonaws.com/net-mozaws-stage-fx-test-travis-ci-artifacts/mozilla/FoxPuppet/1256/1256.3/py27.html. Perhaps @jrbenny35 mioght be able to help here? Maybe it's a locator change that landed in mozilla-central.

**Comment by davehunt** [comment]
I wonder if the failure is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1471713

**Comment by davehunt** [comment]
If so, we could try changing the locator to `tracking-protection-icon-box` for Firefox >= 63, or setting `toolkit.cosmeticAnimations.enabled` to `False`.

**Comment by davehunt** [comment]
Looks like the latter has helped. See #183. I'll leave this open in case there was another reason for the change.

**Comment by davehunt** [comment]
Oops. Said I'd leave it open and then immediately closed it! 🙄

**Pull request closed without merging**
