### PR TITLE
Enable headless Firefox for beta and developer edition

### PR DESCRIPTION
**Pull request by davehunt**
Let's see if we can enable headless for beta and dev now.

### CODE REVIEW

**Comment by davehunt** [comment]
Oops, we already tried this in #113. I'll be patient and wait for 57 to hit beta/dev.

**Comment by davehunt** [comment]
hmm.. now nightly is failing on test_tracking_protection_shield which seems unrelated to this pull request. any thoughts @jrbenny35?

**Comment by jrbenny35** [comment]
> hmm.. now nightly is failing on test_tracking_protection_shield which seems unrelated to this pull request. any thoughts

Looks like the page never loaded. Ran it again and it passed. 

I never liked the idea of using washingtonpost but it seems to work most of the time.

**Comment by davehunt** [comment]
> Looks like the page never loaded. Ran it again and it passed.

I had assumed something more sinister as it was both the nightly jobs that failed. I've retriggered the build so we should hopefully be able to merge this. Once Firefox Quantum is released, we can make ESR the only exception to headless mode.

**Pull request merged**
